[package]
name = "synthesis"
version = "0.1.0"
authors = ["chris <chris.aturd@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.46"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"
meval = "0.2"
