/** Declaration file generated by dts-gen */
import * as React from "react";


export class InlineTex extends React.Component {
    constructor(...args: any[]);

    render(): any;

    static defaultProps: {
        texContent: string;
        texSeperator: string;
    };

}

export class Tex extends React.Component {
    constructor(...args: any[]);

    render(): any;

    static defaultProps: {
        texContent: string;
        texSeperator: string;
    };
    
}

export namespace InlineTex {
    const isMounted: any;

    const isReactComponent: {
    };

    const replaceState: any;

    function forceUpdate(callback: any): void;

    function render(): any;

    function setState(partialState: any, callback: any): void;

    namespace forceUpdate {
        const prototype: {
        };

    }

    namespace render {
        const prototype: {
        };

    }

    namespace setState {
        const prototype: {
        };

    }
}

export namespace Tex {
    const isMounted: any;

    const isReactComponent: {
    };

    const replaceState: any;

    function forceUpdate(callback: any): void;

    function render(): any;

    function setState(partialState: any, callback: any): void;

    namespace forceUpdate {
        const prototype: {
        };

    }

    namespace render {
        const prototype: {
        };

    }

    namespace setState {
        const prototype: {
        };

    }

}

