export const redBg: string;
export const headerFont: string;
export const grow: string;
export const textOffset: string;
export const horizontalContainer: string;
export const outputContainer: string;
export const outputHeader: string;
export const inputError: string;
export const tabsButton: string;
